spring:
  application:
    name: "Spring boot application"
  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/test
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: sa
#    password: password
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
#  profiles:
#    active: @profileActive@
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
server:
  port: 8080

